import Head from 'next/head'

import Navbar from '@/components/Navbar/Navbar'
import Nav from '@/components/Navbar/Nav';
import About from '@/components/About/About'

export default function Home() {
  return (
    <>
      <Head>
        <title>• Akira | Portfolio •</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <Nav />
        <About />
      </main>
    </>
  )
}
